#!/bin/bash
echo '#--------------------------------------------------------------'
echo '# Pebble SDK Install'
echo '# Linux, Windows (WSL) or Android'
echo '#  -Seth 16/08/2022'
echo '#--------------------------------------------------------------'
echo '# Make sure to install dependencies first:'
echo '# https://github.com/sethasaurus/pebble-sdk-dependencies'
echo '#--------------------------------------------------------------'

#--------------------------------------------------------------------------------------------------------
echo 'Creating dir: ~/pebble-dev'
#--------------------------------------------------------------------------------------------------------
mkdir ~/pebble-dev
cd ~/pebble-dev

#--------------------------------------------------------------------------------------------------------
echo 'Getting resources'
#--------------------------------------------------------------------------------------------------------
wget https://github.com/aveao/PebbleArchive/raw/master/SDKCores/sdk-core-4.3.tar.bz2
wget https://developer.rebble.io/s3.amazonaws.com/assets.getpebble.com/pebble-tool/pebble-sdk-4.5-linux64.tar.bz2

#--------------------------------------------------------------------------------------------------------
echo 'Unzipping SDK'
#--------------------------------------------------------------------------------------------------------
tar xvfj pebble-sdk-4.5-linux64.tar.bz2
rm pebble-sdk-4.5-linux64.tar.bz2
cd ~/pebble-dev/pebble-sdk-4.5-linux64/
touch NO_TRACKING

#--------------------------------------------------------------------------------------------------------
echo 'Updating Path'
#--------------------------------------------------------------------------------------------------------
echo 'export PATH=~/pebble-dev/pebble-sdk-4.5-linux64/bin:$PATH' >> ~/.bashrc &&. ~/.bashrc

#--------------------------------------------------------------------------------------------------------
echo 'Fixing a couple of things'
#--------------------------------------------------------------------------------------------------------
if [ "$(grep 'pebble-sdk-homebrew' requirements.txt)" ]; then cp requirements.txt requirements.txt.OLD; grep -v pypkjs requirements.txt.OLD > requirements.txt; echo 'git+https://github.com/pebble/pypkjs.git' >> requirements.txt; fi

#--------------------------------------------------------------------------------------------------------
echo 'Replacing pebble-tool'
#--------------------------------------------------------------------------------------------------------
if [ "$(grep 'sdk.getpebble.com' pebble-tool/pebble_tool/sdk/manager.py)" ]; then sudo mv pebble-tool pebble-tool.OLD; sudo git clone https://github.com/pebble-dev/pebble-tool.git; fi

#--------------------------------------------------------------------------------------------------------
echo 'Installing virtualenv'
#--------------------------------------------------------------------------------------------------------
[ -e .env ] || virtualenv .env
. .env/bin/activate
python2.7 -m pip install https://github.com/pyparsing/pyparsing/releases/download/pyparsing_2.4.7/pyparsing-2.4.7.tar.gz
python2.7 -m pip install -r requirements.txt
python2.7 -m pip install -r pebble-tool/requirements.txt
deactivate

#pebble sdk install ~/Downloads/sdk-core-4.3.tar.bz2

echo '#----------------------------------------------'
echo
echo 'If you are installing on Arm, do the next step'
echo 'https://github.com/sethasaurus/pebble-sdk-arm'
echo
echo 'Otherwise, you're done! Time to test the SDK'a
echo
echo 'Run the following to create a test project:'
echo 'pebble new-project test'
echo 'cd test'
echo 'pebble build'
echo 'pebble install --emulator=aplite'
echo
echo '#----------------------------------------------'


